### ISSUE TITLE
Misorientation Axis

### ISSUE THREAD

**Issue by Eddahbi** [mtex-toolbox/mtex#72]
![question_pagina_1](https://cloud.githubusercontent.com/assets/11910591/8339893/210b544a-1abb-11e5-8fdf-ce019c844dd8.jpg)
![question_pagina_2](https://cloud.githubusercontent.com/assets/11910591/8339907/30821288-1abb-11e5-976e-1c5471483cf3.jpg)
![question_pagina_3](https://cloud.githubusercontent.com/assets/11910591/8339908/31cbb25c-1abb-11e5-86f9-a5ce106bbba0.jpg)
![question_pagina_4](https://cloud.githubusercontent.com/assets/11910591/8339910/32d55dec-1abb-11e5-9a3b-4b4dba779de8.jpg)

**Comment by ralfHielscher** [comment]
Could you please add as plain text MTEX commands you used.

Ralf

**Comment by Eddahbi** [comment]
Hi Ralf,

I used the following commands (as you know 2631 and 1822 are  Ids associated to grains A and B depicted in my EBSD map)
In may case I used the expression g=gB*inv(gA) since the matrix are expressed by the passive rotations which is similar to  g=inv(gB)*gA using MTEX where the matrix are expressed by the active rotations.

grA=grains(2631).meanOrientation
grB=grains(1822).meanOrientation
misAB=inv(grB)*grA
AnAB=misAB.angle /degree
AxAB=misAB.axis
AxAB=round(misAB.axis)

Another question arising from above is that when computing B towards A the result is divergent, instead  the axis must be the same .

Thank you
Eddahbi

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

I do not understand what is wrong. Lets try to make a minimal example.
```matlab
cs1 = crystalSymmetry('m-3m')
cs2 = crystalSymmetry('3')

ori1 = orientation('Euler',10*degree,30*degree,14*degree,cs1)
ori2 = orientation('Euler',22*degree,43*degree,94*degree,cs2)

mori1 = inv(ori1) * ori2;
mori2 = inv(ori2) * ori1;
```
This gives us two misorientations ```mori1``` is a coordinate transform from ```cs2``` to ```cs1``` and ```mori2```  is a coordinate transform from ```cs1``` to ```cs2```.
``` matlab
mori1.axis
```
gives the rotational axis in cs1 while
``` matlab
mori2.axis
```
gives the rotational axis in cs2. In order to compare them we have to look for the x,y,z representation 
```matlab
Miller(mori1.axis,'xyz')
Miller(mori2.axis,'xyz')
```
which gives
```
ans = Miller (show methods, plot)
 size: 1 x 1
 symmetry: m-3m
  x  0.3405
  y -0.9401
  z -0.0188

ans = Miller (show methods, plot)
 size: 1 x 1
 symmetry: 3, X||a*, Y||b, Z||c
  x -0.3405
  y  0.9401
  z  0.0188
```
and we see that they share (up to sign) common x,y,z coordinates with respect to the crystal reference frames of cs1 and cs2.

Maybe you was interested in the misorientation axis with respect to the sample coordinate system. This is computed by
```matlab
axis(ori1,ori2)
axis(ori2,ori1)
```
which both give the same result modulo sign.

I hope this helps.

Ralf.

**Comment by Eddahbi** [comment]
Hi Ralf
Thank you for answer.

No, I don’t need the misorientation with respect to the sample reference, instead with respect to crystal reference.

The example given above does not answer to my doubt. I mentioned that I found 
h=-1.4, k=-1.272 and l=2.53 following the matricial calculation, using the 24 symmetry operators for cubique system. However, MTEX.4.0.23 gives h=-1.272, k=-1.4 and l=2.53.
Yo see that the values of h and k are interchanged. I suspect two thinks for this dilemma; or some symmetry operator is not correct in MTEX or the formula used to calculated (h) is really that of (k) and vice versa. 
As soon as possible, I will try to project a detailed example using EBSD in order to clarify this issue.
Thank you very much
Eddahbi

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

but h=-1.4, k=-1.272, l=2.53  and h=-1.272, k=-1.4, l=2.53 are symmetrically equivalent. The rotational axis with respect to the crytsal referance frame can be determined only up to crystalSymmetry. Thus the resultsa might be ok

**Comment by Eddahbi** [comment]
Thank you Ralf,
Yes, undoubtedly both are symmetrically equivalent, but the matter is that in both cases we obtain the same misorientation matrix (g) and supposedly we apply the same crystal symmetry operation (Oc) to (g); Oc*g, and finally the same relations (as expressed above) for the determination of the coordinates of the axis (hkl). Thus, in theory it must give the same value, and not two symmetrically equivalent ones.
Anyway, in this weekend I will expose a working example where I´ll try to highlights these dilemmas. 

Thank you very much
Eddahbi

**Comment by Eddahbi** [comment]
Hi Ralf,

I see that with the new MTEX-4.1 beta3 the result is compared to MTEX-4.0.23, but the some think remains wrong.
Please, can you send me all the Symmetry Operators used by MTEX for cubic, tetragonal and hexagonal systems, as well as the relations used to calculate the coordenates of misorirentation axis. It is just to verify the results before exposing the example.

Thank you
Eddahbi

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

you can access the symmetry elements of any symmetry group by
```matlab
rotation(crystalSymmetry('432'))
```
The code for computing the misorientation axis can be found [here](https://github.com/mtex-toolbox/mtex/blob/master/geometry/%40orientation/axis.m). It essentialy projects the orientation into the fundamental region and then takes the ordinary rotational axis.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

can I close this issue?

Ralf.

**Comment by Eddahbi** [comment]
Hi Ralf,

Sorry, now I´m out of my office; and I could not  continue  with this
issue. So, you can close it now, and then when  I´ll come back in on mounth
I´ll try to expose the examples.


Thank you
Eddahbi

2015-07-28 9:14 GMT+02:00 Ralf Hielscher <notifications@github.com>:

> Hi Eddahbi,
>
> can I close this issue?
>
> Ralf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtex-toolbox/mtex/issues/72#issuecomment-125479203>.
>



-- 

*Mohamed OuLahcen, Eddahbi*

*Postdoc-Researcher*

*Department of Physics*

*University Carlos III of Madrid*

*Phone: +34 91 6246261*

**Comment by ralfHielscher** [comment]
Hi Eddahbi,

I found two bugs in former versions of MTEX which I fixed in mtex-4.1.beta6. Could you check whether this fixes your problem as well?

Ralf.

**Comment by Eddahbi** [comment]
Hi Ralf,

Thank you for your continous help.


I did attempts with MTEX 4.1 beta6 but, unfortunately, the problem is still
present. Also, another problem emerges is that the misorientation axis when
computing from a grain A to B or from grain B to A must be the same but in
opposite sense, however MTEX gives equivalent axis which not correct.


Thank you again
Mohamed


2015-08-26 16:32 GMT+02:00 Ralf Hielscher <notifications@github.com>:

> Hi Eddahbi,
>
> I found two bugs in former versions of MTEX which I fixed in
> mtex-4.1.beta6. Could you check whether this fixes your problem as well?
>
> Ralf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtex-toolbox/mtex/issues/72#issuecomment-135041604>.
>



-- 

*Mohamed OuLahcen, Eddahbi*

*Postdoc-Researcher*

*Department of Physics*

*University Carlos III of Madrid*

*Phone: +34 91 6246261*

**Comment by ralfHielscher** [comment]
Hi Mohamed,

have you an example for this? For me
```matlab
ori1 = orientation.rand(100,crystalSymmetry('m-3m'))
ori2 = orientation.rand(100,crystalSymmetry('6mm'))
max(norm(axis(ori1,ori2) + axis(ori2,ori1)))
```
gives a something about 1e-15. This looks like the most general case to me.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Mohamed,

the previous post was about the misorientation axis in specimen coordinates. If you consider the misorientation axis in crystal coordinates - this is computed by the command
```
axis(inv(o1)*o2)
```
according to my understanding this axis can only be determined up to crystal symmetry (the disjoint of the symmetries of o1 and o2). I'l try to explain this below. If you are using a different definition of the misorientation axis let me know.

Assume we want to compute the axis of a misorientation ```mori = inv(o1) * o2```. To my understanding one has to find the rotation ```rot``` with minimum rotational angle that is symmetricaly equivalent to mori and take its rotational axis ```a```. However, the rotation with minimum rotational angle is not uniquely defined but for all symmetry elements ```S``` out of the disjoint of the symmetry groups of o1 and o2 the misorientation ```inv(S) * rot * S``` is symmetrical equivalent to ```mori``` and has the same rotational angle as ```rot```. As a consequence, with ```a``` being the rotational axis of ```rot``` also ```S*a``` is a valid misorientation axis and, hence, misorientation axes with respect to the crystal reference frame are well defined only up to symmetry of the disjoint of both crystal symmetries.

According to all my tests the misorientation axes of ```axis(mori)``` and ```-axis(inv(mori))``` are equal up to symmetry.

May be you could also explain your problem a bit more in detail.

Ralf.

**Comment by ralfHielscher** [comment]
Hi Mohamed,

I once again checked all your messages and came to the conclusion that your idea of the misorientation axis beeing unambiguously defined is not correct. Therefore, I'm going to close the issue. 

If you have additional remarks do not hesitate posting the.

Ralf.

**Comment by Eddahbi** [comment]
Dear Ralf,



Sorry for the delay to continue with this issue.



As I mentioned in a previous message, now I´m out of the university for a
stay, when I come back I will send you a detailed example comparing the
results between my method and MTEX and then together we can elucidate the
way to reveal the misunderstanding.



In parallel, I´m sure that the misorientation axis used in the method is
completely correct (expressed by PASSIVE ROTATION), and it is similar to
the one used by MTEX (expressed by ACTIVE ROTATION), however the result
seems to be different.



Just work a simple example, to bring an orientation O1 to coincide with
orientation O2 or vice versa the O2 to coincide with O1 in the crystal
reference, the misorientaion axis in the first case (h,kl,) must be the
conjugate of the second (-h,-k,-l) which is the same. This fact is
reproduced by the method by MTEX gives a different result.



As soon as possible, I will contact you when I return back to my work



Thank you very much for help

Mohamed



2015-09-03 13:31 GMT+02:00 Ralf Hielscher <notifications@github.com>:

> Hi Mohamed,
>
> I once again checked all your messages and came to the conclusion that
> your idea of the misorientation axis beeing unambiguously defined is not
> correct. Therefore, I'm going to close the issue.
>
> If you have additional remarks do not hesitate posting the.
>
> Ralf.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mtex-toolbox/mtex/issues/72#issuecomment-137412668>.
>



-- 

*Mohamed OuLahcen, Eddahbi*

*Postdoc-Researcher*

*Department of Physics*

*University Carlos III of Madrid*

*Phone: +34 91 6246261*
